### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by gillens** [jemisonf/jemisonf.github.io#1]
Cool website! 
Noticed a few small things:

On this page: https://fgj.codes/projects/web_base.html

- The link with text "link style" goes to https://fgj.codes/projects/, a 404

On this page: https://fgj.codes/projects/fgj.codes.html

- GitHub link at top of page is https://github.com/jemisonf.github.io, should probably be  https://github.com/jemisonf/jemisonf.github.io

- "didn’t any guarantees" could be "didn't have any guarantees"

**Comment by jemisonf** [comment]
Thanks for the contribution @gillens!
